#lfuse     := skipped
#hfuse     := skipped
#efuse     := skipped
#clock     := 8000000
#mmcu      := atmega8
#mmcudef   := $(mmcu)
#fuseClock := 100kHz
#srcDirs   := src lib/src
#cflags    := -Os -Wall -Werror -Wextra
#prog      := default programmer from ~/.avrduderc
#port      := not specified
#progClock := programmer default

include lib/make/*.mk
